name: CI/CD Pipeline for Node.js Microservice

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # You can adjust the Node.js version here

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (if any tests are available)
      - name: Run tests
        run: npm test

      # Deploy to Render (or another service like Heroku)
      - name: Deploy to Render
        uses: render-examples/deploy-node@v1
        with:
          render-token: 'rnd_NghBYNy6xdXCXaUS5mZhfmRvvQH9'
          service-id: 'srv-cv8t9apu0jms73a5kq4g'
