name: CI/CD Pipeline for Node.js Microservice

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.9.0' 

      # Install dependencies
      - name: Install dependencies
        run: npm install

     
      # Deploy to Render 
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          api-key: 'rnd_NghBYNy6xdXCXaUS5mZhfmRvvQH9'
          service-id: 'srv-cv8t9apu0jms73a5kq4g'
